### ISSUE TITLE
(fleet provisioning): Feature to change the certificate path

### ISSUE THREAD

**Issue by satoxiw** [aws-greengrass/aws-greengrass-fleet-provisioning-by-claim#27]
**Feature Description**
In Greengrass Easy setup, the `-cert-path` option allows you to specify the location where the certificate generated during setup is stored, although this is not shown in the documentation [github issue](https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/971) & [github pr](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1305).

**Use Case**
The ability to specify a storage location for certificates obtained through fleet provisioning as well would make certificate management more flexible and easier to deal with when a device is reset.

**Proposed Solution**
Add an optional YAML configuration parameter such as `certRootPath` and if this parameter is set, the location of the certificate file is `certRootPath` instead of `rootPath`.

**Other**
N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by alter-mage** [comment]
Hi

Thanks for reaching out to us and apologies for the radio silence on this issue. For this issue, I would recommend installing Greengrass using an initial configuration and setting the root CA path in that file. Please find an example of the same on this [installation](https://docs.aws.amazon.com/greengrass/v2/developerguide/fleet-provisioning.html#run-greengrass-core-v2-installer-fleet) page.

**Comment by satoxiw** [comment]
The method you described is the path where the root CA is placed, and I believe that the certificates generated after provisioning are unconditionally placed directly under `rootPath` in the current implementation. The intention is to control this placement position.

**Comment by jcosentino11** [comment]
Yep, certs are placed relative to `rootPath` currently.  

I noticed you checked the box for implementing, if you'd like to contribute a PR, I'd be happy to review: should be a matter of adding an [optional configuration](https://github.com/aws-greengrass/aws-greengrass-fleet-provisioning-by-claim/blob/655b063e1e09fd928ead7add13a512204e0d27a5/src/main/java/com/aws/greengrass/FleetProvisioningByClaimPlugin.java#L62) and then overriding the rootPath config later on.

**Comment by satoxiw** [comment]
@jcosentino11 I apologise for not responding to your comments here for a long period of time. I had been able to fix the problem in my local environment and had confirmed that it was working, but I missed the timing to PR it. The fix now seems to be in progress and I will wait with anticipation for this merge. Thank you!

**Comment by jcosentino11** [comment]
Glad to hear you're unblocked! PR has been merged and will need to go through testing before release
